# typed: true
# frozen_string_literal: true

# This file was generated by Brewtap. DO NOT EDIT.
class Jjava < Formula
  desc "Jupyter kernel for executing java code"
  homepage "https://github.com/m-dzianishchyts/jjava"
  url "https://github.com/m-dzianishchyts/jjava/releases/download/1.0a15/jjava-1.0a15-kernelspec.zip"
  sha256 "cf48b185febc133b35967228735e350a0631fb22fc67c3cb1af266460bf6c5e2"
  license "MIT"

  depends_on "jupyterlab"

  def install
    kernel_path = share/"jupyter/kernels/java"
    kernel_path.install Dir["*"]
  end

  def caveats
    jupyter_path = share/"jupyter"
    jupyter_env = "JUPYTER_PATH"
    <<~EOS
      The installation of the Homebrew package takes place in an isolated environment, so ensure JJava visibility by running:
        echo "$#{jupyter_env}" | grep -qE "(^|:)#{jupyter_path}(:|$)" || { sed -i '/^export #{jupyter_env}=/d' ~/.zshrc; echo "export #{jupyter_env}=${#{jupyter_env}:+$#{jupyter_env}:}#{jupyter_path}" >> ~/.zshrc && source ~/.zshrc; } (macOS)
        echo "$#{jupyter_env}" | grep -qE "(^|:)#{jupyter_path}(:|$)" || { sed -i '/^export #{jupyter_env}=/d' ~/.bashrc; echo "export #{jupyter_env}=${#{jupyter_env}:+$#{jupyter_env}:}#{jupyter_path}" >> ~/.bashrc && source ~/.bashrc; } (Linux)
      Although JJava doesn't depend on java, it requires jre>=11 to run.
      Make sure you have one in your PATH.
    EOS
  end
end
